### ISSUE TITLE
Save thumbnail doesn't work

### ISSUE THREAD

**Issue by hydratioNx99** [sylviiu/ezytdl#102]
For example: When downloading music with "download & convert" and enabling "Save Thumbnail", the video thumbnail doesn't get saved as the mp3 cover.

**Comment by sylviiu** [comment]
Which website are you downloading from? And just confirming, you are saving (or converting) to an mp3, right?

**Comment by hydratioNx99** [comment]
I'm downloading from youtube

![image](https://github.com/sylviiu/ezytdl/assets/29978081/b2080f09-ad64-4468-9ad4-93cb2f3d2dad)

**Comment by sylviiu** [comment]
You need FFmpeg installed in order to also save the thumbnail with the media.

Go to the settings, and click on the download button for FFmpeg for that to be set up :D
![image](https://github.com/sylviiu/ezytdl/assets/95180094/50e9e515-ab78-4a47-a955-9a9df9e31c1b)

**Comment by hydratioNx99** [comment]
I already did that

**Comment by hydratioNx99** [comment]
now I get this error when opening the settings of ezytdl

## Type: Error

### Title: 
Internal error occurred!

### Content: 
{}

SyntaxError: Bad escaped character in JSON at position 21076
    at JSON.parse (<anonymous>)
    at C:\Users\DJ K1RA\AppData\Local\Programs\ezytdl\resources\app.asar\util\currentVersion\pybridge.js:48:40
    at ChildProcess.exithandler (node:child_process:422:7)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)

(no stack)

### Stack: 
```js
- at module.exports (C:\Users\DJ K1RA\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:9:30)
- at module.exports (C:\Users\DJ K1RA\AppData\Local\Programs\ezytdl\resources\app.asar\util\errorHandler.js:8:48)
- at process.<anonymous> (C:\Users\DJ K1RA\AppData\Local\Programs\ezytdl\resources\app.asar\index.js:20:125)
- at process.emit (node:events:513:28)
- at emit (node:internal/process/promises:149:20)
- at processPromiseRejections (node:internal/process/promises:294:27)
- at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

### Below this line, please describe what caused this error.
----
