### ISSUE TITLE
just bcs i can

### ISSUE THREAD

**Issue by ElementShadow** [sylviiu/ezytdl#106]
### Title: 
Internal error occurred!

### Content: 
{}

SyntaxError: Bad escaped character in JSON at position 21098
    at JSON.parse (<anonymous>)
    at X:\SSOFTWARE\ezytdl\resources\app.asar\util\currentVersion\pybridge.js:48:40
    at ChildProcess.exithandler (node:child_process:422:7)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)

(no stack)

### Stack: 
```js
- at module.exports (X:\SSOFTWARE\ezytdl\resources\app.asar\core\sendNotification.js:9:30)
- at module.exports (X:\SSOFTWARE\ezytdl\resources\app.asar\util\errorHandler.js:8:48)
- at process.<anonymous> (X:\SSOFTWARE\ezytdl\resources\app.asar\index.js:20:125)
- at process.emit (node:events:513:28)
- at emit (node:internal/process/promises:149:20)
- at processPromiseRejections (node:internal/process/promises:294:27)
- at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

### Below this line, please describe what caused this error.
----
Error always appear when opening settings

**Comment by sylviiu** [comment]
You can safely ignore that error. This issue does not exist when using the latest nightly / dev build; I'd recommend enabling dev builds in settings (as many more bugs have been fixed there, and you get to try new features!)
