### ISSUE TITLE
Auto-detecting hardware acceleration

### ISSUE THREAD

**Issue by dubstepfuneral** [sylviiu/ezytdl#112]
### Title: 
Failed to determine hardware acceleration capabilities

### Content: 
Could not get video codec of "C:\Users\chill\AppData\Local\Temp\jnBYupeEvzfFJbAnjhtORGFl-sample.mp4"

### Stack: 
```js
- at module.exports (C:\Users\chill\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:9:30)
- at C:\Users\chill\AppData\Local\Programs\ezytdl\resources\app.asar\core\configActions.js:71:25
- at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Below this line, please describe what caused this error.
----
Pressed on the "Auto-Detect" button in settings under "Enable Hardware-Accelerated Video Conversion"

**Comment by sylviiu** [comment]
Issue has been fixed; I improperly configured my domain with GitHub Pages, and nothing was working.

You should be able to try it again and successfully determine the capabilities now, but in the event it doesn't work, reset your DNS cache

[**Windows (Command Prompt):**](https://blog.hubspot.com/website/flush-dns#how-to-flush-dns-windows-10) `ipconfig /flushdns`
[**MacOS (Terminal):**](https://blog.hubspot.com/website/flush-dns#how-to-flush-dns-mac-os-x) `sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder`
(linux varies based on DNS resolver / connection manager)
