### ISSUE TITLE
Failed Download Error

### ISSUE THREAD

**Issue by twooda** [sylviiu/ezytdl#119]
### Title: 
Internal error occurred!

### Content: 
{
    "code": "ERR_INVALID_ARG_TYPE"
}

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received null
    at stat (node:fs:1520:10)
    at t.stat (node:electron/js2c/asar_bundle:2:4626)
    at C:\Users\dairy\AppData\Local\Programs\ezytdl\resources\app.asar\util\promisifiedFS\existsSync.js:4:8
    at new Promise (<anonymous>)
    at module.exports (C:\Users\dairy\AppData\Local\Programs\ezytdl\resources\app.asar\util\promisifiedFS\existsSync.js:3:28)
    at promisified.<computed> [as existsSync] (C:\Users\dairy\AppData\Local\Programs\ezytdl\resources\app.asar\util\promisifiedFS.js:36:26)
    at C:\Users\dairy\AppData\Local\Programs\ezytdl\resources\app.asar\util\ytdlp.js:2177:32

(no stack)

### Stack: 
```js
- at module.exports (C:\Users\dairy\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:9:30)
- at module.exports (C:\Users\dairy\AppData\Local\Programs\ezytdl\resources\app.asar\util\errorHandler.js:8:48)
- at process.<anonymous> (C:\Users\dairy\AppData\Local\Programs\ezytdl\resources\app.asar\index.js:20:125)
- at process.emit (node:events:513:28)
- at emit (node:internal/process/promises:149:20)
- at processPromiseRejections (node:internal/process/promises:294:27)
- at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

### Below this line, please describe what caused this error.
----
Just  downloaded this, was trying to get a video off youtube and I get this error, really not sure what it means lol. Ive tried two different times and both times I got this.

**Comment by sylviiu** [comment]
This is a bug with the current stable release; I believe the fix that worked with others is manually creating the destination folder that the app displays before downloading it.

This issue has been fixed in the latest nightly / dev builds.

Try either of the methods and let me know if it works! :D
