### ISSUE TITLE
I get this error every time I open the app

### ISSUE THREAD

**Issue by iamLightway** [sylviiu/ezytdl#122]
### Title: 
Internal error occurred!

### Content: 
{
    "errno": -4094,
    "code": "UNKNOWN",
    "syscall": "spawn"
}

Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:783:9)
    at Object.execFile (node:child_process:359:17)
    at t.<computed> [as execFile] (node:electron/js2c/asar_bundle:2:2218)
    at C:\Users\iamLightway\AppData\Local\Programs\ezytdl\resources\app.asar\util\currentVersion\pybridge.js:44:27
    at new Promise (<anonymous>)
    at module.exports (C:\Users\iamLightway\AppData\Local\Programs\ezytdl\resources\app.asar\util\currentVersion\pybridge.js:9:55)
    at C:\Users\iamLightway\AppData\Local\Programs\ezytdl\resources\app.asar\core\ipc\system\detailsStr.js:30:63
    at new Promise (<anonymous>)
    at Object.func (C:\Users\iamLightway\AppData\Local\Programs\ezytdl\resources\app.asar\core\ipc\system\detailsStr.js:27:22)

(no stack)

### Stack: 
```js
- at module.exports (C:\Users\iamLightway\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:9:30)
- at module.exports (C:\Users\iamLightway\AppData\Local\Programs\ezytdl\resources\app.asar\util\errorHandler.js:8:48)
- at process.<anonymous> (C:\Users\iamLightway\AppData\Local\Programs\ezytdl\resources\app.asar\index.js:20:125)
- at process.emit (node:events:513:28)
- at emit (node:internal/process/promises:149:20)
- at processPromiseRejections (node:internal/process/promises:294:27)
- at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

### Below this line, please describe what caused this error.
----
Well, this is what I am greeted with after opening the app. It says some internal error and just doesn't work at all.

I installed this maybe a month ago too, and had the same issue

**Comment by sylviiu** [comment]
This issue seems to be related to the yt-dlp bridge.

Try closing the app, heading to `%APPDATA%\ezytdl`, delete the `bridge-win32` folder, and reopen the app. This should give you a new build of yt-dlp

**Comment by iamLightway** [comment]
> This issue seems to be related to the yt-dlp bridge.
> 
> Try closing the app, heading to `%APPDATA%\ezytdl`, delete the `bridge-win32` folder, and reopen the app. This should give you a new build of yt-dlp

Yes, that is the case. Thanks for the help, it's fixed now
