### ISSUE TITLE
[Feature-request] Ability to download multiple urls at once

### ISSUE THREAD

**Issue by JensDeLeersnyderPXL** [sylviiu/ezytdl#124]
Every app that is out there only provides an input field to download a single url, it would be nice if you could submit a list of links separated by example with an enter.

**Comment by sylviiu** [comment]
In the latest nightly build (can be enabled via Settings -> Dev Builds), you can actually input multiple URLs by ALT+Enter (or Shift+Enter, can't remember 😅)

Feel free to give that a shot & let me know if that's what you mean!
