### ISSUE TITLE
Internal error occurred: TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by Advik-B** [sylviiu/ezytdl#132]
### Title: 
Internal error occurred!

### Content: 
{}

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Error'
    --- property 'error' closes the circle
    at JSON.stringify (<anonymous>)
    at process.<anonymous> (C:\Users\Advik\AppData\Local\Programs\ezytdl\resources\app.asar\index.js:20:159)
    at process.emit (node:events:513:28)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:294:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)

(no stack)

### Stack: 
```js
- at module.exports (C:\Users\Advik\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:9:30)
- at module.exports (C:\Users\Advik\AppData\Local\Programs\ezytdl\resources\app.asar\util\errorHandler.js:8:48)
- at process.<anonymous> (C:\Users\Advik\AppData\Local\Programs\ezytdl\resources\app.asar\index.js:19:124)
- at process.emit (node:events:525:35)
- at process._fatalException (node:internal/process/execution:149:25)
```

### Below this line, please describe what caused this error.
----
By clicking on download

**Comment by sylviiu** [comment]
Does this issue always happen when downloading things? What version are you currently on?

**Comment by Advik-B** [comment]
> Does this issue always happen when downloading things?
Yes

> What version are you currently on?
https://github.com/sylviiu/ezytdl/releases/tag/2.4.2

**Comment by sylviiu** [comment]
Sorry for taking so long to get back to you; haven't had motivation for any of my projects lol

Does this issue still appear when using the latest nightly build? (there have been lots of changes between 2.4.2 and the nightly build)

**Comment by Advik-B** [comment]
I lost interest honestly speaking
