### ISSUE TITLE
path does nnot exist

### ISSUE THREAD

**Issue by yeboahkwame** [sylviiu/ezytdl#135]
### Title: 
Error getting info

### Content: 
The path does not exist.

### Stack: 
```js
- at module.exports (C:\Users\Echie Kwame\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:9:30)
- at C:\Users\Echie Kwame\AppData\Local\Programs\ezytdl\resources\app.asar\util\ytdlp.js:865:13
```

### Below this line, please describe what caused this error.
----

**Comment by sylviiu** [comment]
There's nothing I could do to help you solve this issue. Could you please provide more information as to what actually happened?

Closing until then.
