### ISSUE TITLE
720p max quality While video is 1080p ?

### ISSUE THREAD

**Issue by enzomtpYT** [sylviiu/ezytdl#137]
Hello ! Today i witnessed a bug where ezytdl only allow me to download at 720p max on all videos, i checked and the videos allows to watch in 1080p.

Example 
![image](https://github.com/sylviiu/ezytdl/assets/40535918/16674798-360f-45f6-a5eb-6387a1f932bc)
Video i used for the example : https://www.youtube.com/watch?v=x2NQiLvyZKs

FFmpeg version : 6.0
ezytdl yt-dlp bridge version : 2023|222
ezytdl version : 2.4.2
pybridge version : 130 (python  3.11.7 x64)

If any informations is needed i can provide them !

**Comment by sylviiu** [comment]
Switch to dev / nightly builds; they have proper format merging for higher quality downloads! :D

**Comment by enzomtpYT** [comment]
![image](https://github.com/sylviiu/ezytdl/assets/40535918/9193a2b8-d012-41f5-88ca-dcf9e1ebc44d)
![image](https://github.com/sylviiu/ezytdl/assets/40535918/e8f1975d-5186-4763-9096-89298929f45f)
Hello ! I just updated to dev build and the problem is still occuring !

**Comment by sylviiu** [comment]
Right, forgot one step. Back in the settings, make sure you enabled FFmpeg downloading when converting media!
![image](https://github.com/sylviiu/ezytdl/assets/95180094/dcd46e19-d145-476f-8f1a-4cb31a02d5d7)

**Comment by enzomtpYT** [comment]
![image](https://github.com/sylviiu/ezytdl/assets/40535918/eb7e6a43-ad3a-4192-a2f2-7ef731853f6e)
I tried to enable it for downloading medias and it still occurs 😅

**Comment by sylviiu** [comment]
When you start downloading the video, does it provide any information about the resolution / quality?
![image](https://github.com/sylviiu/ezytdl/assets/95180094/7c8a1110-fc6c-4142-be41-7a78facfa477)

**Comment by sylviiu** [comment]
Just tried it on my side, it seems to be downloading at 1080p
![image](https://github.com/sylviiu/ezytdl/assets/95180094/327c0f5c-b02e-48a6-9dc4-6784aeb30ac2)

**Comment by enzomtpYT** [comment]
Oh yeah, okay. I though it would propose me to download in 1080p in the options, sorry for disbturbing you then !

![image](https://github.com/sylviiu/ezytdl/assets/40535918/b266e7ff-60a0-4963-aba2-58157c0c17e2)
