### ISSUE TITLE
Internal error occurred!

### ISSUE THREAD

**Issue by s-wuest** [sylviiu/ezytdl#142]
### Title: 
Internal error occurred!

### Content: 
{}

TypeError: Cannot read properties of null (reading 'latest')
    at C:\Users\stefa\AppData\Local\Programs\ezytdl\resources\app.asar\util\downloadManager.js:403:55
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

(no stack)

### Stack: 
```js
- at module.exports (C:\Users\stefa\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:9:30)
- at module.exports (C:\Users\stefa\AppData\Local\Programs\ezytdl\resources\app.asar\util\errorHandler.js:8:48)
- at process.<anonymous> (C:\Users\stefa\AppData\Local\Programs\ezytdl\resources\app.asar\index.js:20:125)
- at process.emit (node:events:513:28)
- at emit (node:internal/process/promises:149:20)
- at processPromiseRejections (node:internal/process/promises:294:27)
- at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

### Below this line, please describe what caused this error.
----

**Comment by sylviiu** [comment]
please provide the details of where this error originated. i cannot help unless that's provided
