### ISSUE TITLE
JSON at position 20911

### ISSUE THREAD

**Issue by naill975763** [sylviiu/ezytdl#143]
### Title: 
Internal error occurred!

### Content: 
{}

SyntaxError: Bad escaped character in JSON at position 20911 (line 1 column 20912)
    at JSON.parse (<anonymous>)
    at C:\Users\Admin\Downloads\ezytdl-win32\resources\app.asar\util\currentVersion\pybridge.js:48:40
    at ChildProcess.exithandler (node:child_process:422:7)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)

(no stack)

### Stack: 
```js
- at module.exports (C:\Users\Admin\Downloads\ezytdl-win32\resources\app.asar\core\sendNotification.js:24:34)
- at module.exports (C:\Users\Admin\Downloads\ezytdl-win32\resources\app.asar\util\errorHandler.js:8:48)
- at process.<anonymous> (C:\Users\Admin\Downloads\ezytdl-win32\resources\app.asar\index.js:22:125)
- at process.emit (node:events:514:28)
- at emit (node:internal/process/promises:149:20)
- at processPromiseRejections (node:internal/process/promises:294:27)
- at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

### Below this line, please describe what caused this error.
----

**Comment by naill975763** [comment]
Fixed the problem by installing the old version https://github.com/sylviiu/ytdlp-pybridge/releases

**Comment by sylviiu** [comment]
Glad that worked. I'm not at all sure why it's happening in the first place; it's never appeared on my system for any version, but it's appeared for *some* of my friends using other versions. I don't know where to start troubleshooting.

Tracking this issue @ #121
