### ISSUE TITLE
No Thumbnail in Metadata

### ISSUE THREAD

**Issue by gamebeaker** [sylviiu/ezytdl#156]
Hi,
if i download from music.youtube.com with "Best Audio" -> Save Metadata all selected -> Download.
I don't have a Thumbnail in the Metadata. I checked it with [vlc media player](https://www.videolan.org/vlc/) and [mp3tag](https://www.mp3tag.de/en/).

**Comment by sylviiu** [comment]
yeeah :( i was just recently made aware of it in #166 as well - i'm going to go ahead and close this issue to funnel it over to that one so i can keep better track of it
