### ISSUE TITLE
Feature request - Option to enter multiple links for download

### ISSUE THREAD

**Issue by zcraber** [sylviiu/ezytdl#16]
It'd be nice if there is an option to enter multiple links at the same for download. This is particularly useful in cases where a user want to use the same download setting for different links and avoid the need of setting them each time.

**Comment by sylviiu** [comment]
I could definitely look into that... something like a "quick download" page that lets you put in multiple urls and uses a specific quality / conversion for all of them?

**Comment by zcraber** [comment]
> something like a "quick download" page that lets you put in multiple urls and uses a specific quality / conversion for all of them?

I think a separate page is not needed, just allowing entering multiple URLs would be sufficient. Something like this:

![image](https://github.com/sylviiu/ezytdl/assets/61133303/aec381f2-8363-4238-a006-ad3d0de14e10)

Thank you.

**Comment by sylviiu** [comment]
Got it! I'll look into implementing that.

**Comment by sylviiu** [comment]
I've made a quick implementation on what I think works well for entering multiple URLs at a time.

https://github.com/sylviiu/ezytdl/assets/95180094/4d9efe99-5378-4334-a160-67b0e527e40c

You'd add a URL to the list of URLs by pressing `ALT` + `ENTER` (or `CMD` + `ENTER` on Mac) -- same behavior on Convert tab as well. Playlists will be parsed as usual, those entries will be appended to the end of the list.

How's something like this?

**Comment by zcraber** [comment]
Awesome!

**Comment by sylviiu** [comment]
Cool! This'll be in the next nightly build (runs in around 3 hours from now) :D
