### ISSUE TITLE
you SMELL bad

### ISSUE THREAD

**Issue by antonblast** [sylviiu/ezytdl#2]
https://github.com/sylviiu/ezytdl/assets/69024179/34cda956-879a-4bb2-9e35-fb1fb7081be0

**Comment by antonblast** [comment]
https://github.com/sylviiu/ezytdl/assets/69024179/e10312fd-1d02-42d1-914a-15de1ad35f2e

**Comment by catfxngs** [comment]
I have to agree, very glaring issue

**Comment by sylviiu** [comment]
that's like the github equivalent of an uno reverse card i think

**Comment by catfxngs** [comment]
can you uno reverse this ratio
