### ISSUE TITLE
Error while downloading multiple Spotify albums

### ISSUE THREAD

**Issue by zcraber** [sylviiu/ezytdl#20]
### Title: 
Internal error occurred!

### Content: 
{}

TypeError: Cannot read properties of null (reading 'width')
    at C:\Users\zcraber's PC\AppData\Local\Programs\ezytdl\resources\app.asar\util\downloadManager.js:291:99
    at Array.sort (<anonymous>)
    at createDownloadObject (C:\Users\zcraber's PC\AppData\Local\Programs\ezytdl\resources\app.asar\util\downloadManager.js:291:83)
    at C:\Users\zcraber's PC\AppData\Local\Programs\ezytdl\resources\app.asar\util\downloadManager.js:490:55
    at Array.map (<anonymous>)
    at C:\Users\zcraber's PC\AppData\Local\Programs\ezytdl\resources\app.asar\util\downloadManager.js:490:46
    at new Promise (<anonymous>)
    at Object.createDownload (C:\Users\zcraber's PC\AppData\Local\Programs\ezytdl\resources\app.asar\util\downloadManager.js:484:74)
    at Object.func (C:\Users\zcraber's PC\AppData\Local\Programs\ezytdl\resources\app.asar\core\ipc\queue\download.js:7:76)
    at IpcMainImpl.<anonymous> (C:\Users\zcraber's PC\AppData\Local\Programs\ezytdl\resources\app.asar\core\ipcHandler.js:26:25)

(no stack)

### Stack: 
```js
- at module.exports (C:\Users\zcraber's PC\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:24:34)
- at module.exports (C:\Users\zcraber's PC\AppData\Local\Programs\ezytdl\resources\app.asar\util\errorHandler.js:8:48)
- at process.<anonymous> (C:\Users\zcraber's PC\AppData\Local\Programs\ezytdl\resources\app.asar\index.js:20:125)
- at process.emit (node:events:513:28)
- at emit (node:internal/process/promises:149:20)
- at processPromiseRejections (node:internal/process/promises:294:27)
- at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

### Below this line, please describe what caused this error.
----
Added several Spotify album links and clicked download.

![image](https://github.com/sylviiu/ezytdl/assets/61133303/eeb1a05e-6613-4c94-add5-74bbf46ea211)

**Comment by sylviiu** [comment]
I KNEW I OVERLOOKED SOMETHING

i'll try to fix this before next nightly 😅

**Comment by sylviiu** [comment]
Can you provide the album links you used? Testing it with some albums on my side worked fine, I can only assume it's an edge case

![image](https://github.com/sylviiu/ezytdl/assets/95180094/a8fb9a69-613d-4b1b-8ec4-d84f0e76d360)

**Comment by zcraber** [comment]
> Can you provide the album links you used?

Sure. I could reproduce this issue every time with Spotify albums and playlists. Are there any additional logs or info I should provide to get this issue sorted?

1. https://open.spotify.com/album/4BJDDA3huLb2rcWv1qZGX5?si=mdgGNnXxTGuLKaY-rbp2yQ
2. https://open.spotify.com/album/11NN8DpabJQfPfuBsHIp9S?si=f5qxc_hEQsO-PrqSAN90Cg
3. https://open.spotify.com/album/4XXOc8YizUIsibvn3ao40J?si=A2cOc6soQNq_m8b6fjrF3w
4. https://open.spotify.com/album/1Ts9N5BkZurlZeEmevjyFx?si=qHZD3aHfRAiOwUT58Sfsww

**Comment by sylviiu** [comment]
that's... strange?
![image](https://github.com/sylviiu/ezytdl/assets/95180094/9a67ff64-560e-48fc-a6d8-024cffd51b0a)

I don't think I've put any *useful* logs to help troubleshoot that

I do feel like the most recent commits I've pushed could possibly fix this issue? (I feel like it's related to the issues I fixed -- before, the thumbnails never registered for the first playlist entries / entry of a batch URL query, that's been fixed)

I could try to push one more commit that may *directly* address this error, and have you try a test build?

**Comment by zcraber** [comment]
> have you try a test build?

This is from the nightly build 2.5.0-dev.122.

**Comment by sylviiu** [comment]
I created a workflow that builds the app (without releasing it) for testing.

Could you try to [download, extract and run this test build artifact](https://github.com/sylviiu/ezytdl/actions/runs/5608235836) (compressed in a zip file, ~300mb) and see if the issue has been resolved? (or if there is a new error from said fix?)

**Comment by zcraber** [comment]
No worries! You've developed such a wonderful tool nevertheless. 

It did resolve that error, but it showed another error `failed to download`. Should I provide the entire error? Because it mentioned I shouldn't create an issue for that error.

**Comment by sylviiu** [comment]
> Because it mentioned I shouldn't create an issue for that error.

hmm.. i believe this is standard error output for yt-dlp, did the error appear when you tried to download? or was it when you were gathering the info from the playlists?

**Comment by zcraber** [comment]
It appeared when I tried to download.

**Comment by zcraber** [comment]
> it might be possible to fix when searching for a youtube equivalent of a spotify track, but i'm not sure how to determine if something is actually viewable... i'd have to look into it

I noticed that the `failed to download` error occurs only when trying to download multiple albums at once. They can be downloaded individually if that helps.

**Comment by sylviiu** [comment]
That's strange... does the error show the URL it tried to download by any chance?

**Comment by zcraber** [comment]
Yes, it showed error like this for all tracks:

`yt-dlp failed to download https://open.spotify.com/track/3KtXPo010piTIrBQDZFInz [1]`

**Comment by sylviiu** [comment]
...aaand this issue opens back up 😅 it should not be trying to download the original Spotify link

I'll look into it a little bit later. I have a feeling I know what's happening

**Comment by sylviiu** [comment]
THIS TIME I think it's fixed. I made sure to thoroughly test it, I'm pretty sure everything works okay now.

https://github.com/sylviiu/ezytdl/assets/95180094/649da76d-1212-49a5-9377-e51888b0d412

*only a minor amount of hair was pulled throughout the debugging of this issue i swear*
