### ISSUE TITLE
Video Size Information

### ISSUE THREAD

**Issue by anasabdulmoghny** [sylviiu/ezytdl#202]
I would really like it if I could see the size of the video/audio before downloading

**Comment by sylviiu** [comment]
if you're referring to using the quick/full download button, there was another issue recently that focused on adding a resolution selection for it - see #224

however, you can download individual formats that were supplied by the source site - if yt-dlp was able to parse a video resolution and/or audio bitrate, those should be visible!
![image](https://github.com/user-attachments/assets/cf3d942f-bbab-4e3c-8805-2ae2daf6fb57)

will close this issue to focus the idea of quality selection full downloading - if i'm assuming wrong, feel free to reopen!
