### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by xmha97** [sylviiu/ezytdl#25]
Thanks for UI and UX and Animations.
Please add light mode.

![image](https://github.com/sylviiu/ezytdl/assets/23485114/0ab0490b-665a-42de-9623-6a992bfb7825)

![image](https://github.com/sylviiu/ezytdl/assets/23485114/2095cc6c-a85d-4966-b44d-6be7c6c26f8c)

**Comment by sylviiu** [comment]
I'm on board with adding a light theme, but it'd definitely take some time.

I'll go ahead and pin this issue to mark it as a "work-in-progress"

**Comment by sylviiu** [comment]
little bit of progress :D

![image](https://github.com/sylviiu/ezytdl/assets/95180094/ec1ee10b-6d5e-4714-9d4b-bae181e9768b)
![image](https://github.com/sylviiu/ezytdl/assets/95180094/831c1051-e5e7-45ad-9ad3-14ad7c509bcc)
![image](https://github.com/sylviiu/ezytdl/assets/95180094/2e9f0a35-58a7-4c3c-9121-50a628074f5e)

**Comment by sylviiu** [comment]
Light theme has been added! This will be in the next dev build :D
