### ISSUE TITLE
Add proxy option

### ISSUE THREAD

**Issue by xmha97** [sylviiu/ezytdl#26]
Hi, I can use the proxy on yt-dlp and youtube-dl
Please add the proxy option.

**Comment by sylviiu** [comment]
Will do!

**Comment by sylviiu** [comment]
Proxy settings option has been added!

![image](https://github.com/sylviiu/ezytdl/assets/95180094/88652719-44f4-458f-8156-6cdf4d43c08c)
![image](https://github.com/sylviiu/ezytdl/assets/95180094/23e719e7-e68d-46c7-bdf2-8c37bdbdc998)

please note that the proxy option adds another `--proxy` command line arg for yt-dlp, so i'd suggest [not using the `--proxy` option manually](https://github.com/sylviiu/ezytdl/issues/27) if you're going to use this option in the settings

**Comment by xmha97** [comment]
Thanks for adding this feature.
Please release a new version.
YouTube is blocked in my country and I need this feature.

**Comment by sylviiu** [comment]
This is now in the latest nightly (dev) version

**Comment by xmha97** [comment]
Thanks 🙏
