### ISSUE TITLE
Remember Extra yt-dlp arguments

### ISSUE THREAD

**Issue by xmha97** [sylviiu/ezytdl#27]
Please remember Extra yt-dlp arguments:

![image](https://github.com/sylviiu/ezytdl/assets/23485114/266bb6aa-9d50-429e-9791-a13cf9f72aae)

After restarting the app, this textbox cleared.

**Comment by sylviiu** [comment]
...after doing some testing, I also realize the additional arguments were never actually passed to yt-dlp. i will also fix that.

**Comment by sylviiu** [comment]
yt-dlp arguments will now be remembered starting with the next nightly build! (in around 2.5 hours from now) :D

**Comment by xmha97** [comment]
Thanks
