### ISSUE TITLE
Minimize button called when window doesn't exist

### ISSUE THREAD

**Issue by catfxngs** [sylviiu/ezytdl#3]
Error occurs at launch when running AppImage or building from source. Issue is _exclusively_ on **1.1.7+** builds. Previous releases function as expected. 

**OS: Fedora Linux 37 (Workstation)**

![image](https://media.discordapp.net/attachments/1107529262271041566/1108050314550059058/image.png)

**Comment by sylviiu** [comment]
I'm pretty sure I figured it out. This is a linux-only issue.

You have a "stunted" instance running in the background -- the app started running, but an error occurred in the middle of starting it. When you run a new instance, it detects that the stunted instance is still running, and the stunted instance then tries to bring the window back to the front (to prevent starting multiple instances)

This is most likely to the implementation of the `sharp` library -- on linux, this requires your system to have `libvips` installed.

`sharp` is supposed to throw an error stating that it couldn't find it (which it did), but the error handler was only initiated afterwards, leaving the process in a state of limbo. Running it from the terminal will only then show the error of missing that library.

I'll throw in a fix to the bringToFront function, but I'll create a system requirements checker to let you know if you're missing a specific library or system requirement. I should've kept in mind that it uses a library many may not have on their system.
