### ISSUE TITLE
Error when trying to download 400 song playlist

### ISSUE THREAD

**Issue by Dominik159E0** [sylviiu/ezytdl#40]
### Title: 
Internal error occurred!

### Content: 
{}

TypeError: Cannot read properties of undefined (reading 'items')
    at parse (C:\Users\Dzomoslav\AppData\Local\Programs\ezytdl\resources\app.asar\util\platforms\spotify.js:27:79)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

(no stack)

### Stack: 
```js
- at module.exports (C:\Users\Dzomoslav\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:9:30)
- at module.exports (C:\Users\Dzomoslav\AppData\Local\Programs\ezytdl\resources\app.asar\util\errorHandler.js:8:48)
- at process.<anonymous> (C:\Users\Dzomoslav\AppData\Local\Programs\ezytdl\resources\app.asar\index.js:20:125)
- at process.emit (node:events:513:28)
- at emit (node:internal/process/promises:149:20)
- at processPromiseRejections (node:internal/process/promises:294:27)
- at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

### Below this line, please describe what caused this error.
----

I am basically trying to download my big playlist for offline use, I did put my client id and secret, I put the url and click the button to start downloading.
Then I get this and it stays stuck on 100 songs retrieved
![obrázok](https://github.com/sylviiu/ezytdl/assets/90928810/9f72b1cd-5b58-4dd5-8569-f16c07c086e2)
The playlist I am trying to download is this one: https://open.spotify.com/playlist/5jSrJsEhXRQXQKjVz5gj0L?si=7f57539aa1f14c5d

**Comment by sylviiu** [comment]
This was fixed in the latest nightly build. Try running that and downloading this playlist again.

**Comment by Dominik159E0** [comment]
Thank you it now works.
