### ISSUE TITLE
Unable to convert any video to MP3

### ISSUE THREAD

**Issue by ppurplux** [sylviiu/ezytdl#42]
Getting the error "Could not convert the audio stream to AAC -- Target codec not supposed by installed build of FFmpeg"

FFmpeg build 20230806
ezytdl yt-dlp bridge 20230716
![902a4be7-42f9-42fe-913f-0c5a6c077a6a](https://github.com/sylviiu/ezytdl/assets/69032098/f4fb1e19-57a5-4914-a0ca-3615e00e4fd4)

**Comment by sylviiu** [comment]
I remember this error, I do think it was fixed. Try to download the [latest release](https://github.com/sylviiu/ezytdl/releases/tag/2.4.2) and try again; I think that version had a broken update script.

**Comment by ppurplux** [comment]
This fixed it for me. Thank you for the solution! ♥
