### ISSUE TITLE
Did I do something wrong?

### ISSUE THREAD

**Issue by gkokaisel** [sylviiu/ezytdl#43]
### Title: 
Internal error occurred!

### Content: 
{}

TypeError: Cannot read properties of undefined (reading 'items')
    at parse (C:\Users\gkoka\AppData\Local\Programs\ezytdl\resources\app.asar\util\platforms\spotify.js:27:79)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

(no stack)

### Stack: 
```js
- at module.exports (C:\Users\gkoka\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:9:30)
- at module.exports (C:\Users\gkoka\AppData\Local\Programs\ezytdl\resources\app.asar\util\errorHandler.js:8:48)
- at process.<anonymous> (C:\Users\gkoka\AppData\Local\Programs\ezytdl\resources\app.asar\index.js:20:125)
- at process.emit (node:events:513:28)
- at emit (node:internal/process/promises:149:20)
- at processPromiseRejections (node:internal/process/promises:294:27)
- at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

### Below this line, please describe what caused this error.
----

**Comment by sylviiu** [comment]
Nope! I believe you're trying to download a Spotify playlist / album with >100 entries? If so, this issue has been fixed in the latest [nightly build](https://github.com/sylviiu/ezytdl/releases/tag/3.0.0-dev.138). Try that and let me know if that fixes it.

**Comment by gkokaisel** [comment]
Wow! I didn't expect a reply from you. Enjoy this program! That makes
sense. I updated it but still got the same error. It's a really large
playlist, though, with 372 songs. I'll break it up. For reference,
https://open.spotify.com/playlist/6x1FBXPNLJMavoqyaahJNx?si=828363981ce24835


Thanks again!

**Comment by sylviiu** [comment]
Absolutely no problem! I'm passionate about this app, so I'm definitely going to try to respond to every issue; I'm glad you enjoy it!

I'm a little lost, though. I'm able to load the playlist just fine...
![image](https://github.com/sylviiu/ezytdl/assets/95180094/7bbe2b04-98a5-42cc-9ff6-3db62a990ec2)

Can you do me a favor and upload a screenshot of the version details found in the settings? This would help me narrow it down.
![image](https://github.com/sylviiu/ezytdl/assets/95180094/6eae8f1e-2927-414a-8f34-e413a3ffb734)

**Comment by gkokaisel** [comment]
Well, there you go, I have v. 2.4.2. I went to the link you gave me and
that is what I saw to download.
[image: image.png]

**Comment by gkokaisel** [comment]
Yep, working just fine with that build. So sorry for the oversight on my
part!

**Comment by sylviiu** [comment]
It's no worries! Glad it's working :D
