### ISSUE TITLE
Internal Error with ERR_INVALID_ARG_TYPE in ytdlp Application

### ISSUE THREAD

**Issue by GrandDiJay** [sylviiu/ezytdl#48]
### Title: 
Internal error occurred!

### Content: 
{
    "code": "ERR_INVALID_ARG_TYPE"
}

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received null
    at stat (node:fs:1520:10)
    at t.stat (node:electron/js2c/asar_bundle:2:4626)
    at C:\Users\GrandDiJay\AppData\Local\Programs\ezytdl\resources\app.asar\util\promisifiedFS\existsSync.js:4:8
    at new Promise (<anonymous>)
    at module.exports (C:\Users\GrandDiJay\AppData\Local\Programs\ezytdl\resources\app.asar\util\promisifiedFS\existsSync.js:3:28)
    at promisified.<computed> [as existsSync] (C:\Users\GrandDiJay\AppData\Local\Programs\ezytdl\resources\app.asar\util\promisifiedFS.js:36:26)
    at C:\Users\GrandDiJay\AppData\Local\Programs\ezytdl\resources\app.asar\util\ytdlp.js:2177:32

(no stack)

### Stack: 
```js
- at module.exports (C:\Users\GrandDiJay\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:9:30)
- at module.exports (C:\Users\GrandDiJay\AppData\Local\Programs\ezytdl\resources\app.asar\util\errorHandler.js:8:48)
- at process.<anonymous> (C:\Users\GrandDiJay\AppData\Local\Programs\ezytdl\resources\app.asar\index.js:20:125)
- at process.emit (node:events:513:28)
- at emit (node:internal/process/promises:149:20)
- at processPromiseRejections (node:internal/process/promises:294:27)
- at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

### Below this line, please describe what caused this error.
----
I tried downloading playlists and some videos. i also got this error on other devices

**Comment by sylviiu** [comment]
What version did you use? Could you provide the link used for downloading?

**Comment by sylviiu** [comment]
closing due to no response

(additionally, i couldn't find any useful code from this stack trace; try updating the app via the latest github releases download)

**Comment by GrandDiJay** [comment]
> closing due to no response
> 
> (additionally, i couldn't find any useful code from this stack trace; try updating the app via the latest github releases download)

Hey there, sorry for the delay in getting back to you. My WiFi hasn't been great for the last 8 days, so I couldn't respond earlier. I think I used the regular 2.4.1 release from GitHub.

**Comment by sylviiu** [comment]
Could you try again using either the [2.4.2 release](https://github.com/sylviiu/ezytdl/releases/tag/2.4.2) or the [latest nightly build?](https://github.com/sylviiu/ezytdl/releases/tag/3.0.0-dev.158)
