### ISSUE TITLE
This is a great project. Can you provide a tutorial to introduce the architecture design of this project?

### ISSUE THREAD

**Issue by webhwh** [sylviiu/ezytdl#51]
This is a great project. Can you provide a tutorial to introduce the architecture design of this project?

**Comment by sylviiu** [comment]
I've never done one of those before (I'm still new to public open source projects, it's all very new to me lol)

What exactly would the tutorial entail?

**Comment by webhwh** [comment]
haha sigh。。。
actually I want to know why yt-dlp starts so fast. I used to use Electron to start yt-dlp very slowly. My English is poor, and I am not good at Electron, so it is difficult for me to understand your code without any notes...
If there are any comments or video tutorials explaining the code architecture, I would greatly appreciate it..
Supplement This project is too cool. Thank you for your open source efforts

**Comment by sylviiu** [comment]
Ah! I apologize for my incredibly messy code lol, I need to make commenting a habit.

It's actually not an optimization in Node.JS / Electron that made yt-dlp start very fast; it was actually a [Python bridge I wrote for yt-dlp](https://github.com/sylviiu/ytdlp-pybridge); the method I use is somewhat "hacky," but it definitely had a good turnout.

The Python bridge's main purpose is to allow the executable to be ran once (and continue running until closed), and basically provide a "constantly running yt-dlp launcher" -- the goal of it was to load all of the libraries required by yt-dlp during startup, so every yt-dlp command can be executed instantly by that running process without slowing down your computer with loading all of the libraries needed each time a command was run.

While it was in early development, I made a little comparison between using standard yt-dlp (left side, v1.0) and the Python bridge (right side, v2.0+)

https://github.com/sylviiu/ezytdl/assets/95180094/57dc7152-4170-4bfa-a464-b5a2f0fdd23b

https://github.com/sylviiu/ezytdl/assets/95180094/213431d6-359f-4ebd-a71a-dd545d21491d

The bridge also implements Python's threading system, so each command that is executed will spawn asynchronously while maintaining only one running process -- 12 downloads in the app would've spawned 12 different processes if it were using yt-dlp itself, whereas it keeps a single process using the bridge.

**Comment by webhwh** [comment]
thank you for helping me， you are so kind
no wonder I don't understand. I haven't used Python before  -- lol,
a very impressive Python bridge, I guess it might be faster to use Java or C++for the bridge?
although I don't even know lol

**Comment by sylviiu** [comment]
> a very impressive Python bridge, I guess it might be faster to use Java or C++for the bridge?
> although I don't even know lol

It could be faster, but I chose Python because yt-dlp is also written in Python - there is an entire Python API exposed by yt-dlp (and upstream) for developers to integrate, which also simplified the library loading.

(and in my testing, even with 7 concurrent downloads, the bridge doesn't use many resources; Python seems to be working perfectly in terms of speed :D)

**Comment by webhwh** [comment]
(and in my testing, even with 7 concurrent downloads, the bridge doesn't use many resources; Python seems to be working perfectly in terms of speed :D)

> thank you for helping me， you are so kind谢谢你帮助我，你太善良了 no wonder I don't understand. I haven't used Python before -- lol,难怪我不明白。我以前没有使用过Python——哈哈， a very impressive Python bridge, I guess it might be faster to use Java or C++for the bridge?一个非常令人印象深刻的 Python 桥，我想使用 Java 或 C++ 对于桥可能更快？ although I don't even know lol虽然我什至不知道哈哈

**Comment by webhwh** [comment]
ohh, very cooooool ...  continuous attention

**Comment by GunGunGun** [comment]
> > a very impressive Python bridge, I guess it might be faster to use Java or C++for the bridge?
> > although I don't even know lol
> 
> It could be faster, but I chose Python because yt-dlp is also written in Python - there is an entire Python API exposed by yt-dlp (and upstream) for developers to integrate, which also simplified the library loading.
> 
> (and in my testing, even with 7 concurrent downloads, the bridge doesn't use many resources; Python seems to be working perfectly in terms of speed :D)

I think it's best to submit your patch to yt-dlp repo, because if this get integrate into yt-dlp it's a win-win for us, so much improvement can be made from using this bridge honestly, mpv and other project that makes use of yt-dlp also benefit from it which is amazing!

**Comment by sylviiu** [comment]
> I think it's best to submit your patch to yt-dlp repo, because if this get integrate into yt-dlp it's a win-win for us

Not sure that's a goal for them; the bridge is functionally a wrapper for yt-dlp, and being as niche of a use case it is I'd think it's best to keep them separate. I don't intend to submit a patch myself, if I'm going to be honest.

However, I don't mind submitting a patch with a similar function to this if a contributor of yt-dlp says it'd be a good addition beforehand, but again, I don't think it's one of their goals.

**Comment by GunGunGun** [comment]
> > I think it's best to submit your patch to yt-dlp repo, because if this get integrate into yt-dlp it's a win-win for us
> 
> Not sure that's a goal for them; the bridge is functionally a wrapper for yt-dlp, and being as niche of a use case it is I'd think it's best to keep them separate. I don't intend to submit a patch myself, if I'm going to be honest.
> 
> However, I don't mind submitting a patch with a similar function to this if a contributor of yt-dlp says it'd be a good addition beforehand, but again, I don't think it's one of their goals.

We should try to discuss with @pukkandan, honestly in practice being able to run yt-dlp as system service is such a big deal because it eliminates slow startup time, and if we make use of requests/urllib3's ConnectionPool we gain even more speed, this is huge for media players with yt-dlp backend like mpv.

**Comment by pukkandan** [comment]
yt-dlp is primarily a CLI tool, not a service/daemon and we provide a Python API for extendability. This project is basically a JRPC wrapper for a persistent yt-dlp and has a completely different user interface. It makes zero sense for this to part of yt-dlp itself.

**Comment by StefanLobbenmeier** [comment]
Not sure how much of the performance is gained by the python JIT startup opposed to regular yt-dlp initialization, but it might make sense to do an official yt-dlp-daemon similar to how [mvnd](https://github.com/apache/maven-mvnd) or [gradle](https://docs.gradle.org/current/userguide/gradle_daemon.html) work if it turns out having a yt-dlp daemon is all that is needed
