### ISSUE TITLE
Error getting info

### ISSUE THREAD

**Issue by sbaindha** [sylviiu/ezytdl#55]
### Title: 
Error getting info

### Content: 
The path does not exist.

### Stack: 
```js
- at module.exports (C:\Users\hp\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:24:34)
- at C:\Users\hp\AppData\Local\Programs\ezytdl\resources\app.asar\util\ytdlp.js:932:13
```

### Below this line, please describe what caused this error.
----

**Comment by sylviiu** [comment]
Please describe what caused the error when opening new issues. I have no information as to what caused this.

Will re-open when more information is provided.
