### ISSUE TITLE
what is this error?

### ISSUE THREAD

**Issue by ARIFERCOS** [sylviiu/ezytdl#59]
### Title: 
Internal error occurred!

### Content: 
{}

TypeError: Cannot read properties of undefined (reading 'items')
    at parse (C:\Users\Arif Ercos\AppData\Local\Programs\ezytdl\resources\app.asar\util\platforms\spotify.js:27:79)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

(no stack)

### Stack: 
```js
- at module.exports (C:\Users\Arif Ercos\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:9:30)
- at module.exports (C:\Users\Arif Ercos\AppData\Local\Programs\ezytdl\resources\app.asar\util\errorHandler.js:8:48)
- at process.<anonymous> (C:\Users\Arif Ercos\AppData\Local\Programs\ezytdl\resources\app.asar\index.js:20:125)
- at process.emit (node:events:513:28)
- at emit (node:internal/process/promises:149:20)
- at processPromiseRejections (node:internal/process/promises:294:27)
- at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

### Below this line, please describe what caused this error.
----

**Comment by sylviiu** [comment]
This is due to a bugged Spotify playlist pagination implementation in earlier versions of ezytdl. A fix is currently available in the [latest nightly release](https://github.com/sylviiu/ezytdl/releases/tag/3.0.0-dev.167); try again with this build.

Closing for now; if it doesn't work, I'll reopen.
