### ISSUE TITLE
"code": "UNKNOWN",

### ISSUE THREAD

**Issue by micro2547** [sylviiu/ezytdl#63]
### Title: 
Internal error occurred!

### Content: 
{
    "errno": -4094,
    "code": "UNKNOWN",
    "syscall": "spawn"
}

Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:783:9)
    at Object.execFile (node:child_process:359:17)
    at t.<computed> [as execFile] (node:electron/js2c/asar_bundle:2:2218)
    at C:\Users\micro\AppData\Local\Programs\ezytdl\resources\app.asar\util\currentVersion\pybridge.js:44:27
    at new Promise (<anonymous>)
    at module.exports (C:\Users\micro\AppData\Local\Programs\ezytdl\resources\app.asar\util\currentVersion\pybridge.js:9:55)
    at C:\Users\micro\AppData\Local\Programs\ezytdl\resources\app.asar\util\updateAvailable\pybridge.js:6:87
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

(no stack)

### Stack: 
```js
- at module.exports (C:\Users\micro\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:9:30)
- at module.exports (C:\Users\micro\AppData\Local\Programs\ezytdl\resources\app.asar\util\errorHandler.js:8:48)
- at process.<anonymous> (C:\Users\micro\AppData\Local\Programs\ezytdl\resources\app.asar\index.js:20:125)
- at process.emit (node:events:513:28)
- at emit (node:internal/process/promises:149:20)
- at processPromiseRejections (node:internal/process/promises:294:27)
- at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

### Below this line, please describe what caused this error.
----
I keep getting this error even when i do nothing and I dont know why. My ezytdl program is completely broken and it wont let me download anything or change any settings because of this error.

**Comment by sylviiu** [comment]
This was an issue with the nightly release before the latest, where the electron node version was updated to a version that was incompatible with the zip extraction library used for yt-dlp, causing it to be corrupted.

Head over to `%APPDATA%\ezytdl`, and delete the folder named `bridge-win32`. Once you've done that, download the [latest nightly build](https://github.com/sylviiu/ezytdl/releases/tag/3.0.0-dev.167) and install that. Once you open it, the problem should be fixed.

Let me know if that works for you!

**Comment by micro2547** [comment]
Thanks! This worked and my ezytdl runs fine with no errors now. Appreciate it
