### ISSUE TITLE
:<

### ISSUE THREAD

**Issue by OrchidWarrior** [sylviiu/ezytdl#64]
### Title: 
Internal error occurred!

### Content: 
{
    "errno": -4094,
    "code": "UNKNOWN",
    "syscall": "spawn"
}

Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:783:9)
    at Object.execFile (node:child_process:359:17)
    at Object.execFile (node:electron/js2c/asar_bundle:2:2218)
    at C:\Users\Administrator\Desktop\ezytdl-win32\resources\app.asar\util\currentVersion\ffmpeg.js:23:27

(no stack)

### Stack: 
```js
- at module.exports (C:\Users\Administrator\Desktop\ezytdl-win32\resources\app.asar\core\sendNotification.js:24:34)
- at module.exports (C:\Users\Administrator\Desktop\ezytdl-win32\resources\app.asar\util\errorHandler.js:8:48)
- at process.<anonymous> (C:\Users\Administrator\Desktop\ezytdl-win32\resources\app.asar\index.js:22:125)
- at process.emit (node:events:513:28)
- at emit (node:internal/process/promises:149:20)
- at processPromiseRejections (node:internal/process/promises:294:27)
- at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

### Below this line, please describe what caused this error.
----

**Comment by sylviiu** [comment]
Try the fix described in issue #63. If that doesn't work, let me know and I'll work with you further.
