### ISSUE TITLE
O....O

### ISSUE THREAD

**Issue by OrchidWarrior** [sylviiu/ezytdl#66]
### Title: 
Internal error occurred!

### Content: 
{}

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Error'
    --- property 'error' closes the circle
    at JSON.stringify (<anonymous>)
    at process.<anonymous> (C:\Users\Administrator\AppData\Local\Programs\ezytdl\resources\app.asar\index.js:20:159)
    at process.emit (node:events:513:28)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:294:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)

(no stack)

### Stack: 
```js
- at module.exports (C:\Users\Administrator\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:9:30)
- at module.exports (C:\Users\Administrator\AppData\Local\Programs\ezytdl\resources\app.asar\util\errorHandler.js:8:48)
- at process.<anonymous> (C:\Users\Administrator\AppData\Local\Programs\ezytdl\resources\app.asar\index.js:19:124)
- at process.emit (node:events:525:35)
- at process._fatalException (node:internal/process/execution:149:25)
```

### Below this line, please describe what caused this error.
----

**Comment by sylviiu** [comment]
Can you describe how this happened? What caused this error?

**Comment by OrchidWarrior** [comment]
i just did open the app, DEV and stable version both getting same error. ( mostly when i am trying to download or going to setting )

## Type: Error

### Title: 
Internal error occurred!

### Content: 
{
    "errno": -4094,
    "code": "UNKNOWN",
    "syscall": "spawn"
}

Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:783:9)
    at Object.execFile (node:child_process:359:17)
    at t.<computed> [as execFile] (node:electron/js2c/asar_bundle:2:2218)
    at C:\Users\Administrator\AppData\Local\Programs\ezytdl\resources\app.asar\util\currentVersion\ffmpeg.js:23:27

(no stack)

### Stack: 
```js
- at module.exports (C:\Users\Administrator\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:9:30)
- at module.exports (C:\Users\Administrator\AppData\Local\Programs\ezytdl\resources\app.asar\util\errorHandler.js:8:48)
- at process.<anonymous> (C:\Users\Administrator\AppData\Local\Programs\ezytdl\resources\app.asar\index.js:20:125)
- at process.emit (node:events:513:28)
- at emit (node:internal/process/promises:149:20)
- at processPromiseRejections (node:internal/process/promises:294:27)
- at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

### Below this line, please describe what caused this error.
----
this happened when i tried to download ffmpeg

**Comment by OrchidWarrior** [comment]
doing anything or nothing cause this problem to happen.

**Comment by sylviiu** [comment]
i'm not having this issue myself, nor has anyone else told me about this issue with ffmpeg, so there's not much testing i can do from my end

if this is just relating to ffmpeg, try deleting the `%APPDATA%\ezytdl\ffmpeg-win64` folder, and re-download it in ezytdl. chances are, the download may have stopped prematurely.

**Comment by sylviiu** [comment]
closing to inactivity
