### ISSUE TITLE
Portable version not working (see attachment)

### ISSUE THREAD

**Issue by Synell** [sylviiu/ezytdl#7]
The latest portable built version of the app (v1.1.10) is not starting. I also tried adding the res folder from the source but exact same error.

![image](https://github.com/sylviiu/ezytdl/assets/70210528/74f35943-c336-414c-834a-0252dfe86915)

**Comment by sylviiu** [comment]
*i swear this wasn't an issue before*
![image](https://github.com/sylviiu/ezytdl/assets/95180094/6b0ca94c-4a95-482d-bc1d-4ce833c7d9c6)

i'll try rebuilding it and replacing that file

**Comment by sylviiu** [comment]
I rebuilt it from that release tag, and it seems to be working on my side now. [Try redownloading the portable release](https://github.com/sylviiu/ezytdl/releases/tag/1.1.10), and let me know if it works for you.

**Comment by Synell** [comment]
Yeah it's fixed now, thanks ! ^^
Sorry for late response...
