### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by csegeb** [sylviiu/ezytdl#70]
### Title: 
Internal error occurred!

### Content: 
{}

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Error'
    --- property 'error' closes the circle
    at JSON.stringify (<anonymous>)
    at process.<anonymous> (/Applications/ezytdl.app/Contents/Resources/app.asar/index.js:20:159)
    at process.emit (node:events:513:28)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:294:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)

(no stack)

### Stack: 
```js
- at module.exports (/Applications/ezytdl.app/Contents/Resources/app.asar/core/sendNotification.js:9:30)
- at module.exports (/Applications/ezytdl.app/Contents/Resources/app.asar/util/errorHandler.js:8:48)
- at process.<anonymous> (/Applications/ezytdl.app/Contents/Resources/app.asar/index.js:19:124)
- at process.emit (node:events:525:35)
- at process._fatalException (node:internal/process/execution:149:25)
```

### Below this line, please describe what caused this error.
----
Tried downloading Spotify Playlist

**Comment by sylviiu** [comment]
what version was this on? can you also provide a link to the spotify playlist in question?

most importantly, does this happen again if you try it again

**Comment by csegeb** [comment]
Hi
I have reinstalled and now it is a different error.
MacOS, M1 MB Air


## Type: Error

### Title: 
Internal error occurred!

### Content: 
{}

TypeError: Cannot read properties of undefined (reading 'items')
    at parse (/Applications/ezytdl.app/Contents/Resources/app.asar/util/platforms/spotify.js:27:79)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

(no stack)

### Stack: 
```js
- at module.exports (/Applications/ezytdl.app/Contents/Resources/app.asar/core/sendNotification.js:9:30)
- at module.exports (/Applications/ezytdl.app/Contents/Resources/app.asar/util/errorHandler.js:8:48)
- at process.<anonymous> (/Applications/ezytdl.app/Contents/Resources/app.asar/index.js:20:125)
- at process.emit (node:events:513:28)
- at emit (node:internal/process/promises:149:20)
- at processPromiseRejections (node:internal/process/promises:294:27)
- at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

### Below this line, please describe what caused this error.
----
Link: https://open.spotify.com/playlist/6wtrXR1XA60jTSU7kf1K4b?si=m0iwtaK4R_e6fPccv4Z_cg

**Comment by sylviiu** [comment]
Ah, yeah. This one's a known issue; check [this response](https://github.com/sylviiu/ezytdl/issues/69#issuecomment-1719529745) for how to fix that.

Let me know if that works!

**Comment by sylviiu** [comment]
closing to inactivity
