### ISSUE TITLE
libnotify not detected

### ISSUE THREAD

**Issue by absolutevm** [sylviiu/ezytdl#73]
If the dependency (libnotify) that ezytdl asks for is libnotify4, I believe this support is broken, as I already have it installed.

**Comment by sylviiu** [comment]
i have absolutely no clue why i specify it as an optional dependency, it's not even vital to the app, and it also shows up on my system

will remove in next nightly haha

**Comment by absolutevm** [comment]
oh alright, thought it was for desktop notifications or something, so that's why i made this issue. thanks for clarifying :)

**Comment by sylviiu** [comment]
it's basically the app saying "hey if you don't have this, system notifications won't work" -- it's not a requirement, and there's very little system notifications for it to even matter
