### ISSUE TITLE
yt-dlp failed to complete [sendUpdates]

### ISSUE THREAD

**Issue by Rainman69** [sylviiu/ezytdl#85]
### Title: 
yt-dlp failed to complete [sendUpdates]

### Content: 
[DRM] The requested site is known to use DRM protection. It will NOT be supported.
       Please DO NOT open an issue, unless you have evidence that the video is not DRM protected

### Stack: 
```py
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1702, in __extract_info
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\unsupported.py", line 147, in _real_extract
yt_dlp.utils.ExtractorError: [DRM] The requested site is known to use DRM protection. It will NOT be supported.
       Please DO NOT open an issue, unless you have evidence that the video is not DRM protected

```

### Below this line, please describe what caused this error.
----

**Comment by sylviiu** [comment]
please provide the details of where or how this error originated. i cannot help unless that's provided
