### ISSUE TITLE
Can't download anything :p

### ISSUE THREAD

**Issue by kvirulent** [sylviiu/ezytdl#93]
### Title: 
Internal error occurred!

### Content: 
{
    "code": "ERR_INVALID_ARG_TYPE"
}

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received null
    at stat (node:fs:1520:10)
    at t.stat (node:electron/js2c/asar_bundle:2:4626)
    at C:\Users\retsr\AppData\Local\Programs\ezytdl\resources\app.asar\util\promisifiedFS\existsSync.js:4:8
    at new Promise (<anonymous>)
    at module.exports (C:\Users\retsr\AppData\Local\Programs\ezytdl\resources\app.asar\util\promisifiedFS\existsSync.js:3:28)
    at promisified.<computed> [as existsSync] (C:\Users\retsr\AppData\Local\Programs\ezytdl\resources\app.asar\util\promisifiedFS.js:36:26)
    at C:\Users\retsr\AppData\Local\Programs\ezytdl\resources\app.asar\util\ytdlp.js:2177:32

(no stack)

### Stack: 
```js
- at module.exports (C:\Users\retsr\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:9:30)
- at module.exports (C:\Users\retsr\AppData\Local\Programs\ezytdl\resources\app.asar\util\errorHandler.js:8:48)
- at process.<anonymous> (C:\Users\retsr\AppData\Local\Programs\ezytdl\resources\app.asar\index.js:20:125)
- at process.emit (node:events:513:28)
- at emit (node:internal/process/promises:149:20)
- at processPromiseRejections (node:internal/process/promises:294:27)
- at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

### Below this line, please describe what caused this error.
----

Literally downloading any video causes this error. Version 2.4.2

**Comment by sylviiu** [comment]
i see what's going on. it's trying to find an FFmpeg install when none exists. there are two things you can do to fix this:

- **Install FFmpeg** -- you don't even need to use it for anything, but it'll get rid of this error. it's an odd error though lol
![image](https://github.com/sylviiu/ezytdl/assets/95180094/236f1220-cd4f-4b1b-87f2-84f8a5265f93)

- **Update to a nightly/dev build** -- the nightly build apparently does more checks that avoid this error. you can enable this in the settings and manually check for an update, or you can just download the latest dev build and install it
![image](https://github.com/sylviiu/ezytdl/assets/95180094/c1e880e0-3e33-408d-8611-98b6d75eb203)
![image](https://github.com/sylviiu/ezytdl/assets/95180094/4169e0aa-d5fe-4095-83c9-e3ddcc9f13b4)

let me know if you try either of these, and if they work! will close the issue for now -- if it still persists, i'll reopen

**Comment by kvirulent** [comment]
THANKS!!! It works now :D
